/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx}", "./components/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#bfc9be",
        "surface-bright": "#fcf9f8",
        "surface-container-low": "#f6f3f2",
        "primary": "#005931",
        "inverse-primary": "#88d8a1",
        "outline": "#6f7a70",
        "primary-container": "#217346",
        "secondary-container": "#d0e5d2",
        "on-secondary-container": "#546758",
        "surface-container-highest": "#e5e2e1",
        "surface-container-high": "#eae7e7",
        "surface-container": "#f0eded",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e5e2e1",
        "surface-dim": "#dcd9d9",
        "surface": "#fcf9f8",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#3f4941",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#00210f",
        "on-primary-container": "#a4f5bd",
        "primary-fixed": "#a3f4bc",
        "primary-fixed-dim": "#88d8a1",
        "secondary": "#506354",
        "on-secondary": "#ffffff",
        "tertiary": "#60492b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#7a6141",
        "on-tertiary-container": "#ffdeb8",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0ef",
        "background": "#fcf9f8",
        "on-background": "#1b1c1c",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "surface-tint": "#176c40",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "24px",
        "unit": "8px",
        "margin-desktop": "48px",
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"],
        "headline-xl": ["Manrope", "sans-serif"],
        "label-md": ["IBM Plex Sans", "sans-serif"],
        "label-sm": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};